echo "START Clear"
rm -f ../data/A.lex
rm -f ../data/POS.counts
rm -f ../data/TOK_POS.counts
rm -f ../data/TOK_POS.probs
rm -f ../data/secondoterm.txt
rm -f ../data/transducerTOK_POS.txt
rm -f ../data/transducerTOK_POS_UNK.txt
rm -f ../data/secondTerm.txt
echo "END Clear"