echo "START Clear"
rm -f 1.fst
rm -f ../data/tok_predicted.txt
rm -f ../data/line.fst
rm -f ../data/transducerTOK_POS_UNK.txt
rm -f ../data/transducerTOK_POS.txt
rm -f ../data/transducer.fst
rm -f ../data/tok_actual.txt
rm -f ../data/sentences_line.txt
rm -f ../data/sentences.txt
rm -f ../data/secondTerm.txt
rm -f ../data/pos.lm
rm -f ../data/pos.cnt
rm -f ../data/data.far
rm -f ../data/TOK_POSaux.counts
rm -f ../data/TOK_POS.probs
rm -f ../data/TOK_POS.counts
rm -f ../data/concept.txt
rm -f ../data/A.lex
rm -f ../data/POS.counts
echo "END Clear"
